from typing import Literal

from pydantic import BaseModel, Field, model_validator


CheckpointType = Literal["multiple_choice", "essay"]


class VideoCheckpoint(BaseModel):
    id: str = Field(..., description="Stable identifier for the checkpoint question.")
    timestamp_seconds: int = Field(
        ...,
        ge=0,
        description="Suggested second to pause the video and show the question.",
    )
    type: CheckpointType = Field(
        ...,
        description="Question type. Use multiple_choice or essay.",
    )
    question: str = Field(..., min_length=10, description="Question shown to the student.")
    options: list[str] | None = Field(
        default=None,
        description="Exactly 3 choices when type is multiple_choice.",
    )
    correct_answer: str | None = Field(
        default=None,
        description="Correct answer text for multiple_choice checkpoints.",
    )
    explanation: str | None = Field(
        default=None,
        description="Explanation for the correct answer in multiple_choice checkpoints.",
    )
    keywords: list[str] | None = Field(
        default=None,
        description="Important keywords expected in an essay answer.",
    )
    hint: str | None = Field(
        default=None,
        description="Hint for essay checkpoints.",
    )
    grading_criteria: str | None = Field(
        default=None,
        description="Short grading criteria for essay checkpoints.",
    )

    @model_validator(mode="after")
    def validate_checkpoint_shape(self) -> "VideoCheckpoint":
        if self.type == "multiple_choice":
            if not self.options or len(self.options) != 3:
                raise ValueError("multiple_choice checkpoints must contain exactly 3 options")
            if not self.correct_answer or self.correct_answer not in self.options:
                raise ValueError("correct_answer must match one option for multiple_choice checkpoints")
            if not self.explanation:
                raise ValueError("multiple_choice checkpoints must include explanation")
            if self.keywords or self.hint or self.grading_criteria:
                raise ValueError("multiple_choice checkpoints must not include essay-only fields")

        if self.type == "essay":
            if self.options or self.correct_answer or self.explanation:
                raise ValueError("essay checkpoints must not include multiple_choice fields")
            if not self.keywords or len(self.keywords) == 0:
                raise ValueError("essay checkpoints must include keywords")
            if not self.hint:
                raise ValueError("essay checkpoints must include hint")
            if not self.grading_criteria:
                raise ValueError("essay checkpoints must include grading_criteria")

        return self


class QuestionGenerationPayload(BaseModel):
    video_title: str = Field(..., min_length=3, description="Title for the educational video.")
    checkpoints: list[VideoCheckpoint] = Field(
        ...,
        min_length=1,
        description="Interactive checkpoints generated from the video and transcript.",
    )


class ChatbotConfig(BaseModel):
    system_prompt: str = Field(..., min_length=10)
    context_summary: str = Field(..., min_length=10)


class StoredVideoTranscript(BaseModel):
    video_id: str = Field(..., min_length=1)
    video_title: str = Field(..., min_length=1)
    transcript: str = Field(..., min_length=1)
    chatbot_config: ChatbotConfig


class VideoQuestionResponse(BaseModel):
    video_id: str = Field(..., description="UUID identifier generated by the backend.")
    video_title: str = Field(..., description="Title of the uploaded video.")
    transcript: str = Field(..., description="Transcript extracted from the video.")
    checkpoints: list[VideoCheckpoint] = Field(..., min_length=1)
    chatbot_config: ChatbotConfig


class VideoChatRequest(BaseModel):
    question: str = Field(..., min_length=3, description="Question from the student about the video.")


class VideoChatResponse(BaseModel):
    video_id: str = Field(..., description="UUID identifier of the video.")
    video_title: str = Field(..., description="Stored title of the video.")
    question: str = Field(..., min_length=3)
    answer: str = Field(..., min_length=1)
